-- ##############################################################
-- ## 📜 ÉPICA 0: AUTENTICACIÓN Y PERFILES (BASE)
-- ##############################################################

-- Tabla para almacenar la información recolectada del formulario N8N, vinculada a profiles.
CREATE TABLE public.profile_metrics (
  profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  experience_level TEXT NOT NULL,
  age INT NOT NULL CHECK (age >= 18 AND age <= 100),
  gender TEXT NOT NULL,
  main_goals TEXT NOT NULL CHECK (char_length(main_goals) <= 200),
  main_challenges TEXT NOT NULL CHECK (char_length(main_challenges) <= 200),
  info_habits TEXT[] NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.profile_metrics IS 'Métricas y KPIs recolectados del formulario N8N, vinculados a cada perfil.';

-- Tabla para perfiles extendidos, vinculada a los usuarios de Supabase Auth.
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.profiles IS 'Almacena datos públicos de los perfiles de usuario.';

-- Tabla para definir los roles de la aplicación.
CREATE TABLE public.roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.roles IS 'Define los roles de usuario (ej. principiante, experto).';

-- Tabla de unión para asignar roles a los perfiles.
CREATE TABLE public.user_roles (
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role_id BIGINT NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
  PRIMARY KEY (profile_id, role_id)
);
COMMENT ON TABLE public.user_roles IS 'Asigna uno o más roles a cada perfil de usuario.';

-- Insertar los roles iniciales.
INSERT INTO public.roles (name, description) VALUES
('expert', 'Usuario experto que puede crear cursos y ofrecer servicios.'),
('novice', 'Usuario principiante que consume contenido y participa en la comunidad.');

-- Función automática para crear un perfil a nuevos usuarios.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  -- Crear el perfil del usuario
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger que ejecuta la función después de que un nuevo usuario se registra en Supabase Auth.
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ##############################################################
-- ## 📜 ÉPICA 1: TUTORIALES
-- ##############################################################

-- Tabla para almacenar los tutoriales gratuitos.
CREATE TABLE public.tutorials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  video_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.tutorials IS 'Contenido educativo gratuito creado por expertos.';

-- Tabla para los comentarios en los tutoriales.
CREATE TABLE public.tutorial_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  tutorial_id BIGINT NOT NULL REFERENCES public.tutorials(id) ON DELETE CASCADE,
  parent_comment_id BIGINT REFERENCES public.tutorial_comments(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.tutorial_comments IS 'Comentarios y respuestas de los usuarios en los tutoriales.';

-- Tabla para los "me gusta" en los tutoriales.
CREATE TABLE public.tutorial_likes (
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  tutorial_id BIGINT NOT NULL REFERENCES public.tutorials(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (profile_id, tutorial_id)
);
COMMENT ON TABLE public.tutorial_likes IS 'Registra los "me gusta" de los usuarios en los tutoriales.';


-- ##############################################################
-- ## 💬 ÉPICA 2: COMUNIDAD
-- ##############################################################

-- Tabla para las publicaciones en la comunidad.
CREATE TABLE public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.posts IS 'Publicaciones de los usuarios en el muro de la comunidad.';

-- Tabla para los comentarios en las publicaciones.
CREATE TABLE public.post_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  parent_comment_id BIGINT REFERENCES public.post_comments(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.post_comments IS 'Comentarios y respuestas en las publicaciones de la comunidad.';


-- ##############################################################
-- ## 🎓 ÉPICA 3: CURSOS
-- ##############################################################

-- Tabla para los cursos de pago.
CREATE TABLE public.courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expert_profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  is_published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.courses IS 'Cursos de pago creados por usuarios con rol de experto.';

-- Tabla para las lecciones dentro de cada curso.
CREATE TABLE public.course_lessons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content_text TEXT,
  video_url TEXT,
  lesson_order INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.course_lessons IS 'Lecciones individuales que componen un curso.';

-- Tabla para registrar las inscripciones/compras de cursos por parte de los usuarios.
CREATE TABLE public.course_enrollments (
  profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
  enrolled_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (profile_id, course_id)
);
COMMENT ON TABLE public.course_enrollments IS 'Registra qué usuario está inscrito en qué curso.';


-- ##############################################################
-- ## 🤝 ÉPICA 4: SERVICIOS DE EXPERTOS (SIMPLIFICADO)
-- ##############################################################

-- Perfil extendido para expertos con información para promoción de servicios.
CREATE TABLE public.expert_profiles (
  profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  bio TEXT, -- Biografía o resumen profesional.
  specialties TEXT[], -- Array de especialidades, ej. {'jabones', 'cremas faciales'}
  phone_number TEXT, -- Para contacto vía WhatsApp.
  hourly_rate NUMERIC(10, 2), -- Costo del servicio por hora.
  created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.expert_profiles IS 'Información promocional para que los expertos ofrezcan sus servicios.';


-- ##############################################################
-- ## ⚡ ÍNDICES PARA MEJORAR RENDIMIENTO
-- ##############################################################

-- Índices para claves foráneas comunes para acelerar las consultas.
CREATE INDEX ON public.user_roles (profile_id);
CREATE INDEX ON public.tutorials (profile_id);
CREATE INDEX ON public.tutorial_comments (tutorial_id);
CREATE INDEX ON public.tutorial_comments (profile_id);
CREATE INDEX ON public.tutorial_likes (tutorial_id);
CREATE INDEX ON public.tutorial_likes (profile_id);
CREATE INDEX ON public.posts (profile_id);
CREATE INDEX ON public.post_comments (post_id);
CREATE INDEX ON public.post_comments (profile_id);
CREATE INDEX ON public.courses (expert_profile_id);
CREATE INDEX ON public.course_lessons (course_id);
CREATE INDEX ON public.course_enrollments (course_id);


-- ##############################################################
-- ## 🔧 FUNCIONES RPC PARA N8N
-- ##############################################################

-- RPC function to assign roles by user email (used by N8N).
-- Best practices: prefix name with rpc_, param names prefixed with p_, and use SECURITY DEFINER.

CREATE OR REPLACE FUNCTION public.rpc_assign_role_by_email(
  p_user_email TEXT,
  p_role_name TEXT
)
RETURNS JSON AS $$
DECLARE
  v_profile_id UUID;
  v_role_id BIGINT;
  v_novice_id BIGINT;
BEGIN
  -- Validar datos
  IF p_user_email IS NULL OR p_role_name IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Email y rol requeridos');
  END IF;

  -- Buscar el perfil
  SELECT id INTO v_profile_id FROM public.profiles WHERE id IN (SELECT id FROM auth.users WHERE email = p_user_email);
  IF v_profile_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Usuario no encontrado');
  END IF;

  -- Buscar el rol principal
  SELECT id INTO v_role_id FROM public.roles WHERE name = lower(p_role_name);
  IF v_role_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Rol no encontrado');
  END IF;

  -- Asignar rol principal si no lo tiene
  IF NOT EXISTS (SELECT 1 FROM public.user_roles WHERE profile_id = v_profile_id AND role_id = v_role_id) THEN
    INSERT INTO public.user_roles (profile_id, role_id) VALUES (v_profile_id, v_role_id);
  END IF;

  -- Si es experto, asignar también novato
  IF lower(p_role_name) = 'expert' THEN
    SELECT id INTO v_novice_id FROM public.roles WHERE name = 'novice';
    IF v_novice_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.user_roles WHERE profile_id = v_profile_id AND role_id = v_novice_id) THEN
      INSERT INTO public.user_roles (profile_id, role_id) VALUES (v_profile_id, v_novice_id);
    END IF;
    RETURN json_build_object('success', true, 'user_id', v_profile_id, 'assigned_roles', ARRAY['expert','novice']);
  END IF;

  RETURN json_build_object('success', true, 'user_id', v_profile_id, 'assigned_roles', ARRAY[lower(p_role_name)]);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION public.rpc_assign_role_by_email(TEXT, TEXT) IS 'RPC: Assign role(s) to a user by their email. Assigning "expert" will also assign the "novice" role. Used by automation workflows like N8N.';